name: refresh-table-data
on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 5 * * *'
jobs:
  refresh-table-data:
    runs-on: [self-hosted, Linux, postgresql]
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - run: ./odpt_dump.sh Station | psql -1

