name: refresh-table-data
on:
  push:
    branches:
      - master
  schedule:
    - cron: '31 19 * * *'
jobs:
  refresh-table-data:
    runs-on: [self-hosted, Linux, postgresql]
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          ACL_CONSUMERKEY: ${{ secrets.ACL_CONSUMERKEY }}
        run: |
          ./odpt_dump.sh Station | psql -1
          ./odpt_dump.sh Railway | psql -1

